apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  template:
    spec:
      containers:
        - name: prisma-migrate
          image: foopy7774/gateway-ticket:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ticketapp
                  key: DATABASE_URL
          command: ["npx", "prisma", "migrate", "deploy", "--schema=dist/libs/database/src/lib/schema.prisma"]
      restartPolicy: OnFailure
